### ISSUE TITLE
Make it work with vcsh via tramp?

### ISSUE THREAD

**Issue by QiangF** [renard/magit-view-file#3]
Hi everyone,
Vcsh is a extremely useful software for managing multiple git repositories in the home directory.
Is it possible to get magit-view-file to recognise the repository in a file opened through tramp?

The hack to make vcsh work with magit to access VCSH repo is through TRAMP. Example, open the file /vcsh:zsh:. and then do M-x magit-status.

(add-to-list 'tramp-methods '("vcsh" (tramp-login-program "vcsh")
(tramp-login-args (("enter") ("%h"))) (tramp-remote-shell "/bin/sh")
(tramp-remote-shell-args ("-c"))))

https://labo.olivierdelort.net/bricewge/dotfiles-emacs/blob/9c32a1232708137f7e247c8ceef79826ff9ff933/.emacs.d/bricewge.org

**Comment by renard** [comment]
Hi,
I haven't yet played with vcsh but as long as magit recognize a git repository you might be able to browse it.

**Comment by QiangF** [comment]
I got this error 
let*: Symbol's function definition is void: magit-buffer-file-name
I changed  (file (magit-buffer-file-name t)) to
 (file (magit-file-relative-name))
in the definition of magit-view-file-history.
It works now!
